# Generated by Django 5.2 on 2025-05-13 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_backend', '0019_bankingdeposit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
