# Generated by Django 5.2 on 2025-05-14 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_backend', '0027_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='seller_name',
            new_name='company_name',
        ),
    ]
