# Generated by Django 5.2 on 2025-05-15 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_backend', '0028_rename_seller_name_setting_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='other',
            name='other_type',
            field=models.CharField(choices=[('Fast Expand', 'Fast Expand'), ('Profit', 'Profit'), ('Other', 'Other')], default='Other', max_length=20),
        ),
    ]
