# Generated by Django 5.2 on 2025-05-15 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_backend', '0029_other_other_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankingdeposit',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
