# Generated by Django 5.2 on 2025-05-20 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_backend', '0031_remainingamount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='other',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('credit', 'Credit'), ('debit', 'Debit')], default='debit', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='other',
            name='other_type',
            field=models.CharField(max_length=50),
        ),
    ]
