# Generated by Django 5.2 on 2025-05-20 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_backend', '0031_remainingamount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='other',
            name='other_type',
            field=models.CharField(max_length=50),
        ),
    ]
