# Generated by Django 5.2 on 2025-05-26 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_backend', '0032_other_transaction_type_alter_other_other_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='remainingamount',
            name='last_updated',
        ),
        migrations.AddField(
            model_name='remainingamount',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoice_backend.invoice'),
        ),
    ]
