# Generated by Django 5.2 on 2025-05-20 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_backend', '0032_alter_other_other_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='other',
            name='transaction_type',
            field=models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], default='debit', max_length=10),
        ),
    ]
