# Generated by Django 5.2 on 2025-05-21 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_backend', '0034_alter_other_transaction_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remainingamount',
            name='last_updated',
        ),
        migrations.AddField(
            model_name='remainingamount',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remaining_amounts', to='invoice_backend.buyer'),
        ),
    ]
