# Generated by Django 5.2 on 2025-05-21 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_backend', '0035_remove_remainingamount_last_updated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remainingamount',
            name='buyer',
        ),
        migrations.AddField(
            model_name='remainingamount',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoice_backend.invoice'),
        ),
    ]
