# Generated by Django 5.2 on 2025-05-23 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_backend', '0036_remove_remainingamount_buyer_remainingamount_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='delivery_note_date',
            field=models.DateField(default='2024-01-01'),
        ),
    ]
