# Generated by Django 5.2 on 2025-05-24 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_backend', '0038_alter_invoice_delivery_note_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='delivery_note_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
