# Generated by Django 5.2 on 2025-05-26 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_backend', '0039_alter_invoice_delivery_note_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-created_at']},
        ),
    ]
