# Generated by Django 5.2 on 2025-05-27 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_backend', '0040_alter_invoice_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='company_code',
            field=models.CharField(default='XYZ000', max_length=20),
        ),
    ]
