# Generated by Django 5.2 on 2025-05-27 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_backend', '0041_setting_company_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='hsn_code',
            new_name='hsn_sac_code',
        ),
        migrations.AddField(
            model_name='setting',
            name='HSN_code',
            field=models.IntegerField(default=1, max_length=20),
        ),
        migrations.AddField(
            model_name='setting',
            name='SAC_code',
            field=models.IntegerField(default=1, max_length=20),
        ),
        migrations.AlterField(
            model_name='setting',
            name='company_code',
            field=models.CharField(default='COMPANY000', max_length=20),
        ),
    ]
