# Generated by Django 5.2 on 2025-05-27 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_backend', '0042_rename_hsn_code_invoice_hsn_sac_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='SAC_code',
        ),
    ]
