# Generated by Django 5.2 on 2025-05-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_backend', '0043_remove_setting_sac_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='HSN_code',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
