# Generated by Django 5.2 on 2025-05-28 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_backend', '0044_alter_setting_hsn_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='HSN_code',
        ),
        migrations.AddField(
            model_name='setting',
            name='HSN_codes',
            field=models.JSONField(blank=True, default=list, help_text="List of HSN codes in format: [{'code': '9983', 'description': 'IT Services'}]"),
        ),
    ]
