# Generated by Django 5.2 on 2025-05-28 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_backend', '0045_remove_setting_hsn_code_setting_hsn_codes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='buyer',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='buyer',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Banking', 'Banking')], max_length=10, null=True),
        ),
    ]
