# Generated by Django 5.2 on 2025-05-28 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_backend', '0046_bank_buyer_bank_name_buyer_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='HSN_codes',
            field=models.JSONField(blank=True, default=list, help_text='List of HSN codes'),
        ),
    ]
