# Generated by Django 5.2 on 2025-05-29 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_backend', '0047_alter_setting_hsn_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='companybill',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companybill',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Banking', 'Banking')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='other',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='other',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Banking', 'Banking')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='salary',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salary',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Banking', 'Banking')], max_length=10, null=True),
        ),
    ]
