# Generated by Django 5.2 on 2025-05-31 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_backend', '0048_companybill_bank_name_companybill_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='buyer_gst',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
