# Generated by Django 5.2 on 2025-06-03 05:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_backend', '0049_alter_invoice_buyer_gst'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='deposit_amount',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='invoice_id',
        ),
        migrations.AddField(
            model_name='buyer',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='companybill',
            name='invoice_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='bank_name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='buyer_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='notice',
            field=models.TextField(default='No remarks'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='payment_method',
            field=models.CharField(default='Cash', max_length=100),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='transaction_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='companybill',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='companybill',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='companybill',
            name='notice',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='companybill',
            name='transaction_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='RemainingAmount',
        ),
    ]
