# Generated by Django 5.2 on 2025-05-29 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_backend', '0049_remove_buyer_buyer_name_remove_buyer_deposit_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companybill',
            old_name='deposit_amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='companybill',
            old_name='buyer_name',
            new_name='company_name',
        ),
    ]
