# Generated by Django 5.2 on 2025-06-04 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_backend', '0050_bankaccount_remove_buyer_deposit_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='id',
        ),
        migrations.AlterField(
            model_name='setting',
            name='HSN_codes',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='setting',
            name='account_number',
            field=models.CharField(default='1234567890', max_length=50),
        ),
        migrations.AlterField(
            model_name='setting',
            name='bank_account_holder',
            field=models.CharField(default='Your Name', max_length=255),
        ),
        migrations.AlterField(
            model_name='setting',
            name='bank_name',
            field=models.CharField(default='Bank Name', max_length=255),
        ),
        migrations.AlterField(
            model_name='setting',
            name='company_code',
            field=models.CharField(default='COMP0001', max_length=20),
        ),
        migrations.AlterField(
            model_name='setting',
            name='company_name',
            field=models.CharField(default='Your Company', max_length=255),
        ),
        migrations.AlterField(
            model_name='setting',
            name='ifsc_code',
            field=models.CharField(default='ABCD0123456', max_length=20),
        ),
        migrations.AlterField(
            model_name='setting',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='seller_address',
            field=models.TextField(default='Your Address'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='seller_email',
            field=models.EmailField(default='your@email.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='setting',
            name='seller_gstin',
            field=models.CharField(default='22AAAAA0000A1Z5', max_length=20),
        ),
        migrations.AlterField(
            model_name='setting',
            name='seller_pan',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='setting',
            name='swift_code',
            field=models.CharField(default='SWIFT0001', max_length=20),
        ),
        migrations.AlterField(
            model_name='setting',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
