# Generated by Django 5.2 on 2025-05-30 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_backend', '0050_rename_deposit_amount_companybill_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyer',
            old_name='company_name',
            new_name='buyer_name',
        ),
    ]
