# Generated by Django 5.2 on 2025-05-30 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_backend', '0051_rename_company_name_buyer_buyer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='bank_name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='payment_method',
            field=models.CharField(default='Cash', max_length=50),
        ),
    ]
