# Generated by Django 5.2 on 2025-06-05 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_backend', '0052_alter_setting_seller_pan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='seller_pan',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
