# Generated by Django 5.2 on 2025-06-06 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_backend', '0055_alter_setting_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='exchange_rate',
            field=models.FloatField(blank=True, default=1.0, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='inr_equivalent',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
