# Generated by Django 5.2 on 2025-06-16 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_backend', '0056_invoice_exchange_rate_invoice_inr_equivalent'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='state',
            field=models.CharField(default='Gujarat', max_length=50),
        ),
    ]
