# Generated by Django 5.2 on 2025-06-16 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_backend', '0057_invoice_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='hsn_sac_code',
            field=models.CharField(default='0000', max_length=10),
        ),
    ]
