# Generated by Django 5.2 on 2025-06-16 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_backend', '0058_alter_invoice_hsn_sac_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='hsn_sac_code',
            field=models.CharField(max_length=10),
        ),
    ]
