# Generated by Django 5.2 on 2025-06-19 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_backend', '0059_alter_invoice_hsn_sac_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='country_flag',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
