# Generated by Django 5.2 on 2025-07-01 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_backend', '0065_employee_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='seller_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
